### ISSUE TITLE
cp: target 'Layouts/' is not a directory

### ISSUE THREAD

**Issue by connected201** [andrejkurusiov/keyboard-layout#1]
![image](https://user-images.githubusercontent.com/20506433/158242635-f45e36ae-741c-4ebb-b449-18614b0653fe.png)  
hi, i tried to install, but i unable to execute command. how to fix it? thanks, best regards.

systeminfo:  

`System:    Kernel: 5.10.0-12-amd64 x86_64 bits: 64 compiler: gcc v: 10.2.1`   
 `parameters: BOOT_IMAGE=/vmlinuz-5.10.0-12-amd64 root=UUID=<filter> ro`   
 `quiet splash`   
 `Desktop: KDE Plasma 5.20.5 tk: Qt 5.15.2 wm: kwin_x11 vt: 7 dm: SDDM`   
 `Distro: MX-21_KDE_x64 Wildflower October 20  2021 base: Debian GNU/Linux 11 (bullseye)`

**Comment by andrejkurusiov** [comment]
Hi, please check the path, i.e. how the spaces are handled. I've corrected path names in `cp` command to use quotes around the path with spaces.
Also, you can just press tab to have the prompt escaped for you automatically: https://itectec.com/superuser/how-to-write-space-in-terminal-on-os-x/

**Comment by connected201** [comment]
sorry, with quotes i tried, same results:

![](https://user-images.githubusercontent.com/20506433/158342978-efe25dec-55a8-40c3-a3ae-0a77a44d37f3.png)

**Comment by andrejkurusiov** [comment]
Try using
cp -R "./Cyrillic 2.bundle" ~/Library/Keyboard\ Layouts/

**Comment by connected201** [comment]
Same results, also path `/root/Library/Keyboard Layouts/` i never see in root directory, maybe in debian 11, it's different?

![](https://user-images.githubusercontent.com/20506433/158438292-a026b125-760b-4ad5-aff2-6c52d64583fe.png)

**Comment by connected201** [comment]
your keyboard layout, compatible only with mac OS?

**Comment by andrejkurusiov** [comment]
> your keyboard layout, compatible only with mac OS?

I do not know about Unix/Linux folders regarding layouts, nor layout compatibility. This one is made for mac. Can't help outside of that.
